### ISSUE TITLE
Angular gesture need improve

### ISSUE THREAD

**Issue by bachvtuan** [seanluong/15-puzzle#14]
I tried to move a cell by drag mouse into cell want to move but sometime it works and some time I have to tried 2,3 times.
I guess you can add additional event that is clicking on cell. The solution is very simple. Just click on the cell. I will move to appropriate if possible.
I use below image

![example](https://raw.githubusercontent.com/xuanluong/15-puzzle/master/screenshot.png)

If I click on cell with title is 13, it will be moved down.

**Comment by ghost** [comment]
Hi @bachvtuan 
It's been a while since I worked on this project. If I remember it correctly than the game was not designed to be played with a mouse.

Anyway, your suggestion makes sense. However, I don't think I will back to this project any time soon. It would be great if you could fork the project, implement the feature, and make a pull request later. If you don't have time for it then no problem :).

**Comment by bachvtuan** [comment]
Your project is quite interesting, I'll take a look for it when I have time too.
